// Draft legal documents for the Trust Center. Reference drafts only — must be reviewed by SIQ legal before publishing.
window.AUS_DOCS = {
  terms: {
    pt: { title: 'Termos de uso', lead: 'As regras para usar o Ausculta: o que o serviço faz, o que cabe a você e o que cabe a nós.', sections: [
      ['O que é o Ausculta', ['O Ausculta é um assistente de documentação clínica para médicos-veterinários. Ele grava a consulta com o consentimento do responsável pelo animal, transcreve o áudio e redige um rascunho de prontuário no formato SOAP, com sugestões de ações como peso, alergias, medicamentos, exames e retornos.', 'O serviço é operado pela SIQ [razão social, CNPJ e endereço a confirmar].']],
      ['A IA não substitui o veterinário', ['O rascunho gerado pela IA é uma sugestão. Diagnóstico, prescrição, dose e conduta são decisões do médico-veterinário, que revisa e aprova cada prontuário.', 'Só usuários com registro profissional válido (CRMV no Brasil) podem aprovar prontuários. A aprovação registra nome, número de inscrição, data e hora, em linha com a Resolução CFMV nº 1.321/2020 e suas alterações.']],
      ['Sua conta', ['Você é responsável por manter a senha em sigilo, ativar a verificação em duas etapas quando disponível e informar dados profissionais verdadeiros. Em contas de equipe, o dono da conta define funções e permissões e responde pelos acessos concedidos.', 'Podemos suspender uma conta em caso de uso indevido, fraude, risco à segurança de outros usuários ou falta de pagamento, com aviso prévio sempre que possível.']],
      ['Consentimento para gravar', ['Antes de cada gravação, você confirma quem autorizou: o responsável presente ou a clínica, conforme a política do estabelecimento. É seu dever obter essa autorização e respeitar a recusa. O registro do consentimento fica na trilha de auditoria.']],
      ['Planos, cobrança e cancelamento', ['Os planos, cotas de consultas e preços vigentes aparecem na tela Assinatura. A cobrança é recorrente, por ciclo, na moeda do país da conta. Você pode pausar por até 3 meses ou cancelar a qualquer momento; o acesso continua até o fim do ciclo já pago.', 'O plano Hospital segue contrato próprio, que prevalece sobre estes termos no que for diferente.']],
      ['Seus dados e prontuários', ['Os prontuários pertencem à clínica ou ao veterinário titular da conta. Você pode exportá-los em PDF, JSON ou CSV a qualquer momento. Não vendemos dados nem os usamos para treinar modelos de terceiros.', 'O tratamento de dados pessoais segue a Política de privacidade e, para contas de clínica e hospital, o Acordo de tratamento de dados (DPA).']],
      ['Disponibilidade e limites', ['Trabalhamos para manter o serviço disponível e publicamos o status na Central de Confiança. A gravação funciona offline e sincroniza quando a conexão volta. Não respondemos por decisões clínicas tomadas com base em rascunhos não revisados.']],
      ['Alterações e foro', ['Avisamos por e-mail e no app com pelo menos 30 dias de antecedência sobre mudanças relevantes. Estes termos seguem a lei brasileira, com foro [cidade a confirmar].']]
    ] },
    en: { title: 'Terms of use', lead: 'The rules for using Ausculta: what the service does, what is up to you and what is up to us.', sections: [
      ['What Ausculta is', ['Ausculta is a clinical documentation assistant for veterinarians. With the owner’s consent it records the visit, transcribes the audio and drafts a SOAP record, with suggested actions such as weight, allergies, medications, tests and follow-ups.', 'The service is operated by SIQ [legal name, company ID and address to be confirmed].']],
      ['The AI does not replace the veterinarian', ['The AI draft is a suggestion. Diagnosis, prescription, dose and treatment are decisions of the veterinarian, who reviews and approves every record.', 'Only users with a valid professional license can approve records. Approval stores the name, license number, date and time.']],
      ['Your account', ['You are responsible for keeping your password secret, enabling two-step verification when available and providing accurate professional details. In team accounts, the account owner sets roles and permissions and is accountable for the access granted.', 'We may suspend an account for misuse, fraud, risk to other users or non-payment, with prior notice whenever possible.']],
      ['Consent to record', ['Before each recording you confirm who authorized it: the owner present or the clinic, under the facility’s policy. Obtaining that authorization and respecting a refusal is your duty. The consent record is kept in the audit trail.']],
      ['Plans, billing and cancellation', ['Current plans, visit quotas and prices appear on the Subscription screen. Billing is recurring, per cycle, in the currency of the account’s country. You can pause for up to 3 months or cancel at any time; access continues until the end of the paid cycle.', 'The Hospital plan follows its own contract, which prevails over these terms where they differ.']],
      ['Your data and records', ['Records belong to the clinic or the veterinarian who holds the account. You can export them as PDF, JSON or CSV at any time. We do not sell data or use it to train third-party models.', 'Personal data processing follows the Privacy policy and, for clinic and hospital accounts, the Data processing agreement (DPA).']],
      ['Availability and limits', ['We work to keep the service available and publish its status in the Trust Center. Recording works offline and syncs when the connection returns. We are not liable for clinical decisions based on unreviewed drafts.']],
      ['Changes and jurisdiction', ['We give at least 30 days’ notice by email and in the app before relevant changes. These terms are governed by the law of the account’s country [jurisdiction to be confirmed].']]
    ] },
    es: { title: 'Términos de uso', lead: 'Las reglas para usar Ausculta: qué hace el servicio, qué le corresponde a usted y qué nos corresponde a nosotros.', sections: [
      ['Qué es Ausculta', ['Ausculta es un asistente de documentación clínica para médicos veterinarios. Con el consentimiento del responsable graba la consulta, transcribe el audio y redacta un borrador de historia clínica en formato SOAP, con acciones sugeridas como peso, alergias, medicamentos, estudios y controles.', 'El servicio es operado por SIQ [razón social, identificación fiscal y domicilio a confirmar].']],
      ['La IA no reemplaza al veterinario', ['El borrador de la IA es una sugerencia. Diagnóstico, prescripción, dosis y conducta son decisiones del médico veterinario, que revisa y aprueba cada historia clínica.', 'Solo usuarios con matrícula profesional vigente pueden aprobar historias clínicas. La aprobación registra nombre, matrícula, fecha y hora.']],
      ['Su cuenta', ['Usted es responsable de mantener su contraseña en secreto, activar la verificación en dos pasos cuando esté disponible e informar datos profesionales verdaderos. En cuentas de equipo, el dueño define funciones y permisos y responde por los accesos otorgados.', 'Podemos suspender una cuenta por uso indebido, fraude, riesgo para otros usuarios o falta de pago, con aviso previo siempre que sea posible.']],
      ['Consentimiento para grabar', ['Antes de cada grabación usted confirma quién autorizó: el responsable presente o la clínica, según su política. Obtener esa autorización y respetar una negativa es su deber. El registro del consentimiento queda en la auditoría.']],
      ['Planes, cobro y cancelación', ['Los planes, cupos y precios vigentes aparecen en la pantalla Suscripción. El cobro es recurrente, por ciclo, en la moneda del país de la cuenta. Puede pausar hasta 3 meses o cancelar en cualquier momento; el acceso sigue hasta el fin del ciclo pagado.', 'El plan Hospital sigue un contrato propio, que prevalece sobre estos términos en lo que difiera.']],
      ['Sus datos e historias clínicas', ['Las historias clínicas pertenecen a la clínica o al veterinario titular de la cuenta. Puede exportarlas en PDF, JSON o CSV en cualquier momento. No vendemos datos ni los usamos para entrenar modelos de terceros.', 'El tratamiento de datos personales sigue la Política de privacidad y, para cuentas de clínica y hospital, el Acuerdo de tratamiento de datos (DPA).']],
      ['Disponibilidad y límites', ['Trabajamos para mantener el servicio disponible y publicamos su estado en el Centro de Confianza. La grabación funciona sin conexión y se sincroniza cuando vuelve internet. No respondemos por decisiones clínicas basadas en borradores no revisados.']],
      ['Cambios y jurisdicción', ['Avisamos por correo y en la app con al menos 30 días de anticipación sobre cambios relevantes. Estos términos se rigen por la ley del país de la cuenta [jurisdicción a confirmar].']]
    ] }
  },
  privacy: {
    pt: { title: 'Política de privacidade', lead: 'Quais dados pessoais o Ausculta trata, por quê, por quanto tempo e como você exerce seus direitos pela LGPD.', sections: [
      ['Quem somos e como falar conosco', ['A SIQ [razão social e CNPJ a confirmar] opera o Ausculta. Encarregado de dados (DPO): [nome e e-mail a confirmar].', 'Nos dados de conta dos veterinários, a SIQ é controladora. Nos prontuários, pacientes e responsáveis, a clínica ou o veterinário é o controlador e a SIQ atua como operadora, conforme o DPA.']],
      ['Dados que tratamos', ['Conta: nome, e-mail, telefone, registro profissional, dados de faturamento e preferências.', 'Consulta: áudio, transcrição, rascunho e prontuário aprovado, dados do animal e do responsável (nome, contato, documento quando informado).', 'Uso técnico: dispositivo, versão do app, registros de acesso e da fila de sincronização.']],
      ['Para que usamos', ['Prestar o serviço de documentação, gerar o SOAP e ligar cada frase ao trecho de áudio que a originou; cobrar e emitir notas; dar suporte; manter a segurança e a auditoria; cumprir obrigações legais.', 'Não usamos os dados para publicidade de terceiros, não vendemos dados e não os usamos para treinar modelos de terceiros.']],
      ['Bases legais', ['Execução de contrato para a conta e o serviço; cumprimento de obrigação legal e regulatória, como a guarda do prontuário; legítimo interesse para segurança e prevenção de fraude; consentimento quando exigido, como na gravação da consulta.']],
      ['Com quem compartilhamos', ['Provedores de nuvem, transcrição e IA que processam os dados só para prestar o serviço, sob contrato e sem direito de uso próprio. A lista de suboperadores fica na Central de Confiança e avisamos mudanças com antecedência.', 'Integrações que você mesmo conecta, como PIMS ou IA via MCP, recebem apenas o que você autorizar.']],
      ['Por quanto tempo guardamos', ['Prontuários aprovados: enquanto a conta existir e, no mínimo, pelo prazo de guarda exigido pelo CFMV (5 anos após o último atendimento), com janela de exportação de 12 meses após o encerramento.', 'Áudio: política de retenção em definição com o jurídico. Rascunhos: até a aprovação ou o descarte.']],
      ['Onde os dados ficam', ['Servidores em [país e região a confirmar]. Transferências internacionais, quando ocorrerem, seguem as garantias previstas na LGPD.']],
      ['Seus direitos', ['Você pode pedir confirmação, acesso, correção, portabilidade, anonimização, eliminação e informação sobre compartilhamento, e revogar consentimentos. Pedidos sobre prontuários são encaminhados à clínica controladora. Respondemos em até 15 dias.', 'Você também pode reclamar à Autoridade Nacional de Proteção de Dados (ANPD).']]
    ] },
    en: { title: 'Privacy policy', lead: 'What personal data Ausculta processes, why, for how long and how you exercise your rights.', sections: [
      ['Who we are and how to reach us', ['SIQ [legal name and company ID to be confirmed] operates Ausculta. Data protection officer (DPO): [name and email to be confirmed].', 'For veterinarians’ account data, SIQ is the controller. For records, patients and owners, the clinic or veterinarian is the controller and SIQ acts as processor, under the DPA.']],
      ['Data we process', ['Account: name, email, phone, professional license, billing details and preferences.', 'Visit: audio, transcript, draft and approved record, animal and owner details (name, contact, ID when provided).', 'Technical use: device, app version, access logs and sync queue logs.']],
      ['What we use it for', ['Providing the documentation service, generating the SOAP and linking each sentence to its audio; billing and invoicing; support; security and audit; legal obligations.', 'We do not use data for third-party advertising, do not sell data and do not use it to train third-party models.']],
      ['Legal bases', ['Performance of contract for the account and service; legal and regulatory obligations, such as record retention; legitimate interest for security and fraud prevention; consent where required, such as recording the visit.']],
      ['Who we share with', ['Cloud, transcription and AI providers that process data only to provide the service, under contract and without rights of their own. The subprocessor list is in the Trust Center and we give advance notice of changes.', 'Integrations you connect yourself, such as a PIMS or AI via MCP, receive only what you authorize.']],
      ['How long we keep it', ['Approved records: while the account exists and at least for the retention period required by the veterinary council, with a 12-month export window after closure.', 'Audio: retention policy being defined with legal. Drafts: until approved or discarded.']],
      ['Where data is stored', ['Servers in [country and region to be confirmed]. International transfers, when they occur, follow the safeguards required by applicable law.']],
      ['Your rights', ['You can request confirmation, access, correction, portability, anonymization, deletion and information about sharing, and withdraw consent. Requests about records are forwarded to the controlling clinic. We reply within 15 days.', 'You can also complain to your data protection authority.']]
    ] },
    es: { title: 'Política de privacidad', lead: 'Qué datos personales trata Ausculta, para qué, por cuánto tiempo y cómo ejerce sus derechos.', sections: [
      ['Quiénes somos y cómo contactarnos', ['SIQ [razón social e identificación fiscal a confirmar] opera Ausculta. Delegado de protección de datos (DPO): [nombre y correo a confirmar].', 'En los datos de cuenta de los veterinarios, SIQ es responsable. En historias clínicas, pacientes y responsables, la clínica o el veterinario es el responsable y SIQ actúa como encargado, según el DPA.']],
      ['Datos que tratamos', ['Cuenta: nombre, correo, teléfono, matrícula profesional, datos de facturación y preferencias.', 'Consulta: audio, transcripción, borrador e historia clínica aprobada, datos del animal y del responsable (nombre, contacto, documento cuando se informa).', 'Uso técnico: dispositivo, versión de la app, registros de acceso y de la cola de sincronización.']],
      ['Para qué los usamos', ['Prestar el servicio de documentación, generar el SOAP y vincular cada frase con su audio; cobrar y facturar; dar soporte; mantener la seguridad y la auditoría; cumplir obligaciones legales.', 'No usamos los datos para publicidad de terceros, no los vendemos y no los usamos para entrenar modelos de terceros.']],
      ['Bases legales', ['Ejecución del contrato para la cuenta y el servicio; obligaciones legales y regulatorias, como la conservación de historias clínicas; interés legítimo para seguridad y prevención de fraude; consentimiento cuando se exige, como en la grabación de la consulta.']],
      ['Con quién compartimos', ['Proveedores de nube, transcripción e IA que procesan los datos solo para prestar el servicio, bajo contrato y sin derecho de uso propio. La lista de subencargados está en el Centro de Confianza y avisamos los cambios con anticipación.', 'Las integraciones que usted conecta, como un PIMS o una IA vía MCP, reciben solo lo que usted autorice.']],
      ['Por cuánto tiempo los guardamos', ['Historias clínicas aprobadas: mientras exista la cuenta y como mínimo el plazo exigido por el colegio profesional, con 12 meses para exportar tras el cierre.', 'Audio: política de conservación en definición con el área legal. Borradores: hasta su aprobación o descarte.']],
      ['Dónde se guardan', ['Servidores en [país y región a confirmar]. Las transferencias internacionales, cuando ocurran, siguen las garantías de la ley aplicable (en Argentina, Ley 25.326).']],
      ['Sus derechos', ['Puede solicitar acceso, rectificación, portabilidad, supresión e información sobre el uso compartido, y revocar consentimientos. Las solicitudes sobre historias clínicas se derivan a la clínica responsable. Respondemos en hasta 15 días.', 'También puede reclamar ante la autoridad de protección de datos de su país.']]
    ] }
  },
  dpa: {
    pt: { title: 'Acordo de tratamento de dados (DPA)', lead: 'Para clínicas e hospitais: como a SIQ trata, como operadora, os dados pessoais que a sua organização controla no Ausculta.', sections: [
      ['Papéis', ['A clínica ou hospital é o controlador: decide a finalidade do tratamento, obtém o consentimento para gravar e responde aos titulares. A SIQ é a operadora e trata os dados apenas conforme as instruções documentadas do controlador e este acordo.']],
      ['Objeto e finalidade', ['Gravação, transcrição, estruturação em SOAP, sugestão de ações, armazenamento, auditoria, exportação e integração de dados clínicos solicitados pela clínica e seus usuários autorizados. Inclui suporte, segurança e correção de falhas.']],
      ['Dados e titulares', ['Titulares: responsáveis pelos animais, usuários da clínica e terceiros mencionados na consulta. Dados: identificação e contato, áudio e transcrição, informações clínicas do animal, registros de acesso.']],
      ['Obrigações da SIQ', ['Tratar os dados como confidenciais; limitar o acesso a pessoas autorizadas e sob sigilo; manter as medidas do Relatório de segurança; não usar os dados para treinar modelos próprios ou de terceiros; apoiar o controlador no atendimento aos titulares e em avaliações de impacto.']],
      ['Suboperadores', ['A SIQ pode contratar suboperadores de nuvem, transcrição e IA sob obrigações equivalentes a este acordo. A lista atual fica na Central de Confiança. Mudanças são avisadas com 30 dias de antecedência e a clínica pode se opor com justificativa.']],
      ['Incidentes de segurança', ['A SIQ avisa o controlador sem demora injustificada, em até 24 horas após confirmar um incidente que envolva seus dados, com a natureza, os dados afetados, as medidas tomadas e um contato. Cabe ao controlador comunicar a ANPD e os titulares quando houver risco ou dano relevante, no prazo de 3 dias úteis previsto na Resolução CD/ANPD nº 15/2024; a SIQ fornece as informações necessárias.']],
      ['Auditoria', ['A SIQ disponibiliza relatórios e certificações [a confirmar] e responde a questionários de segurança razoáveis. Auditorias presenciais seguem as condições do contrato Hospital.']],
      ['Fim do contrato', ['Ao encerrar, a clínica tem 12 meses para exportar os dados. Depois, a SIQ elimina os dados, exceto o que precisar guardar por obrigação legal, e confirma a eliminação por escrito se solicitado.']]
    ] },
    en: { title: 'Data processing agreement (DPA)', lead: 'For clinics and hospitals: how SIQ, as processor, handles the personal data your organization controls in Ausculta.', sections: [
      ['Roles', ['The clinic or hospital is the controller: it decides the purpose of processing, obtains consent to record and answers data subjects. SIQ is the processor and handles data only under the controller’s documented instructions and this agreement.']],
      ['Subject matter and purpose', ['Recording, transcription, SOAP structuring, action suggestions, storage, audit, export and integration of clinical data requested by the clinic and its authorized users. Includes support, security and bug fixing.']],
      ['Data and data subjects', ['Data subjects: animal owners, clinic users and third parties mentioned in the visit. Data: identification and contact, audio and transcript, the animal’s clinical information, access logs.']],
      ['SIQ’s obligations', ['Treat data as confidential; limit access to authorized people under confidentiality; maintain the measures in the Security report; not use data to train its own or third-party models; help the controller answer data subjects and with impact assessments.']],
      ['Subprocessors', ['SIQ may engage cloud, transcription and AI subprocessors under obligations equivalent to this agreement. The current list is in the Trust Center. Changes are announced 30 days in advance and the clinic may object with reason.']],
      ['Security incidents', ['SIQ notifies the controller without undue delay, within 24 hours of confirming an incident affecting its data, with its nature, the data affected, measures taken and a contact. The controller notifies the authority and data subjects where required by law; SIQ provides the necessary information.']],
      ['Audits', ['SIQ provides reports and certifications [to be confirmed] and answers reasonable security questionnaires. On-site audits follow the Hospital contract terms.']],
      ['End of contract', ['On termination the clinic has 12 months to export its data. SIQ then deletes the data, except what it must keep by law, and confirms deletion in writing on request.']]
    ] },
    es: { title: 'Acuerdo de tratamiento de datos (DPA)', lead: 'Para clínicas y hospitales: cómo SIQ, como encargado, trata los datos personales que su organización controla en Ausculta.', sections: [
      ['Roles', ['La clínica u hospital es el responsable: decide la finalidad del tratamiento, obtiene el consentimiento para grabar y responde a los titulares. SIQ es el encargado y trata los datos solo según las instrucciones documentadas del responsable y este acuerdo.']],
      ['Objeto y finalidad', ['Grabación, transcripción, estructuración en SOAP, sugerencia de acciones, almacenamiento, auditoría, exportación e integración de datos clínicos solicitados por la clínica y sus usuarios autorizados. Incluye soporte, seguridad y corrección de fallas.']],
      ['Datos y titulares', ['Titulares: responsables de los animales, usuarios de la clínica y terceros mencionados en la consulta. Datos: identificación y contacto, audio y transcripción, información clínica del animal, registros de acceso.']],
      ['Obligaciones de SIQ', ['Tratar los datos como confidenciales; limitar el acceso a personas autorizadas y bajo secreto; mantener las medidas del Informe de seguridad; no usar los datos para entrenar modelos propios o de terceros; apoyar al responsable ante los titulares y en evaluaciones de impacto.']],
      ['Subencargados', ['SIQ puede contratar subencargados de nube, transcripción e IA con obligaciones equivalentes a este acuerdo. La lista vigente está en el Centro de Confianza. Los cambios se avisan con 30 días de anticipación y la clínica puede oponerse con motivo.']],
      ['Incidentes de seguridad', ['SIQ avisa al responsable sin demora indebida, dentro de las 24 horas de confirmar un incidente que afecte sus datos, con su naturaleza, los datos afectados, las medidas tomadas y un contacto. El responsable notifica a la autoridad y a los titulares cuando la ley lo exige; SIQ aporta la información necesaria.']],
      ['Auditoría', ['SIQ pone a disposición informes y certificaciones [a confirmar] y responde cuestionarios de seguridad razonables. Las auditorías presenciales siguen las condiciones del contrato Hospital.']],
      ['Fin del contrato', ['Al finalizar, la clínica tiene 12 meses para exportar los datos. Luego SIQ los elimina, salvo lo que deba conservar por ley, y confirma la eliminación por escrito si se solicita.']]
    ] }
  },
  security: {
    pt: { title: 'Relatório de segurança', lead: 'Os controles técnicos e organizacionais que protegem as consultas, os prontuários e as contas no Ausculta.', sections: [
      ['Criptografia', ['Dados em trânsito protegidos por TLS 1.2 ou superior. Dados em repouso, na nuvem e no dispositivo, cifrados com AES-256. No modo offline, o áudio e o rascunho ficam no armazenamento cifrado do app até sincronizar.']],
      ['Controle de acesso', ['Funções por conta (dono, administrador, veterinário, auxiliar) com o menor privilégio necessário. Só quem tem registro profissional aprova prontuários. Verificação em duas etapas disponível para todos e obrigatória para donos e administradores [a confirmar].']],
      ['Auditoria e integridade', ['Cada aprovação, edição, consentimento, exportação e acesso fica registrado com usuário, data e hora. Prontuários aprovados são selados: correções entram numa nova consulta, sem apagar o original.']],
      ['IA e privacidade', ['A transcrição pode rodar no próprio dispositivo. Quando usa provedores de IA na nuvem, o contrato proíbe retenção para treino e uso próprio dos dados. Nenhuma IA aprova prontuário.']],
      ['Infraestrutura e continuidade', ['Hospedagem em [provedor, país e região a confirmar], com cópias de segurança diárias cifradas e teste periódico de restauração. Monitoramento contínuo de disponibilidade, publicado na Central de Confiança.']],
      ['Desenvolvimento seguro', ['Revisão de código, análise de dependências e separação de ambientes. Testes de intrusão por terceiros [periodicidade a confirmar]. Política de divulgação responsável para pesquisadores [a publicar].']],
      ['Pessoas', ['Acordo de confidencialidade e treinamento de segurança e privacidade para toda a equipe. Acesso da equipe a dados de clientes só para suporte solicitado, registrado na auditoria.']],
      ['Resposta a incidentes', ['Plano de resposta com triagem em até 24 horas, contenção, análise e comunicação aos clientes afetados. Nos casos exigidos pela LGPD, apoio à clínica na comunicação à ANPD e aos titulares em até 3 dias úteis.']]
    ] },
    en: { title: 'Security report', lead: 'The technical and organizational controls that protect visits, records and accounts in Ausculta.', sections: [
      ['Encryption', ['Data in transit protected by TLS 1.2 or higher. Data at rest, in the cloud and on the device, encrypted with AES-256. In offline mode, audio and drafts stay in the app’s encrypted storage until they sync.']],
      ['Access control', ['Per-account roles (owner, administrator, veterinarian, assistant) with least privilege. Only licensed users approve records. Two-step verification available to everyone and required for owners and administrators [to be confirmed].']],
      ['Audit and integrity', ['Every approval, edit, consent, export and access is logged with user, date and time. Approved records are sealed: corrections go into a new visit without erasing the original.']],
      ['AI and privacy', ['Transcription can run on the device itself. When cloud AI providers are used, the contract forbids retention for training and any use of their own. No AI approves a record.']],
      ['Infrastructure and continuity', ['Hosting on [provider, country and region to be confirmed], with daily encrypted backups and periodic restore tests. Continuous availability monitoring, published in the Trust Center.']],
      ['Secure development', ['Code review, dependency scanning and separated environments. Third-party penetration tests [frequency to be confirmed]. Responsible disclosure policy for researchers [to be published].']],
      ['People', ['Confidentiality agreements and security and privacy training for the whole team. Staff access to customer data only for requested support, logged in the audit trail.']],
      ['Incident response', ['Response plan with triage within 24 hours, containment, analysis and notice to affected customers. Where the law requires, we help the clinic notify the authority and data subjects.']]
    ] },
    es: { title: 'Informe de seguridad', lead: 'Los controles técnicos y organizativos que protegen las consultas, las historias clínicas y las cuentas en Ausculta.', sections: [
      ['Cifrado', ['Datos en tránsito protegidos con TLS 1.2 o superior. Datos en reposo, en la nube y en el dispositivo, cifrados con AES-256. Sin conexión, el audio y el borrador quedan en el almacenamiento cifrado de la app hasta sincronizar.']],
      ['Control de acceso', ['Funciones por cuenta (dueño, administrador, veterinario, auxiliar) con el menor privilegio necesario. Solo usuarios matriculados aprueban historias clínicas. Verificación en dos pasos disponible para todos y obligatoria para dueños y administradores [a confirmar].']],
      ['Auditoría e integridad', ['Cada aprobación, edición, consentimiento, exportación y acceso queda registrado con usuario, fecha y hora. Las historias aprobadas se sellan: las correcciones van a una nueva consulta, sin borrar el original.']],
      ['IA y privacidad', ['La transcripción puede ejecutarse en el propio dispositivo. Cuando se usan proveedores de IA en la nube, el contrato prohíbe la retención para entrenamiento y el uso propio de los datos. Ninguna IA aprueba historias clínicas.']],
      ['Infraestructura y continuidad', ['Alojamiento en [proveedor, país y región a confirmar], con copias de seguridad diarias cifradas y pruebas periódicas de restauración. Monitoreo continuo de disponibilidad, publicado en el Centro de Confianza.']],
      ['Desarrollo seguro', ['Revisión de código, análisis de dependencias y ambientes separados. Pruebas de intrusión por terceros [periodicidad a confirmar]. Política de divulgación responsable para investigadores [a publicar].']],
      ['Personas', ['Acuerdo de confidencialidad y capacitación en seguridad y privacidad para todo el equipo. Acceso del equipo a datos de clientes solo para soporte solicitado, registrado en la auditoría.']],
      ['Respuesta a incidentes', ['Plan de respuesta con triage dentro de las 24 horas, contención, análisis y aviso a los clientes afectados. Cuando la ley lo exige, apoyamos a la clínica en la notificación a la autoridad y a los titulares.']]
    ] }
  }
};
